content:
  - name: Homepage
    label: Homepage
    path: static/cms/settings.json
    type: file
    format: json
    fields:
    - name: title
      label: Title
      type: text
      options:
        maxlength: 140
        minLength: 5